

#ifndef __CUSTOM_MEMORYDEVICE__
#define __CUSTOM_MEMORYDEVICE__



#define BOARD_ID                MT6589_EVB

#define CS_PART_NUMBER[0]       KMKJS000VM_B309
#define CS_PART_NUMBER[1]       KMK5U000VM_B309
#define CS_PART_NUMBER[2]       MT29PZZZ8D4WKFEW_18W_6D4_mmd1

#endif /* __CUSTOM_MEMORYDEVICE__ */
